# Generated by Django 5.0.6 on 2024-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoperaciones', '0002_asistentes_legajo_camarografos_legajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='legajo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='camarografos',
            name='legajo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='microfonistas',
            name='legajo',
            field=models.IntegerField(),
        ),
    ]
